//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimCtrlEnumWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(AnimCtrlEnum));
		L.RegVar("CharAnimator", get_CharAnimator, null);
		L.RegVar("CharAnimation", get_CharAnimation, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<AnimCtrlEnum>.Check = CheckType;
		StackTraits<AnimCtrlEnum>.Push = Push;
	}

	static void Push(IntPtr L, AnimCtrlEnum arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(AnimCtrlEnum), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CharAnimator(IntPtr L)
	{
		ToLua.Push(L, AnimCtrlEnum.CharAnimator);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_CharAnimation(IntPtr L)
	{
		ToLua.Push(L, AnimCtrlEnum.CharAnimation);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		AnimCtrlEnum o = (AnimCtrlEnum)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

