//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class AnimCurveNamesWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("AnimCurveNames");
		L.RegVar("IAnimName", get_IAnimName, null);
		L.RegVar("Idle", get_Idle, null);
		L.RegVar("Run", get_Run, null);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IAnimName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AnimCurveNames.IAnimName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Idle(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AnimCurveNames.Idle);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Run(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, AnimCurveNames.Run);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

