//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ParticleOrderAutoSorterWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ParticleOrderAutoSorter), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("UpdateSortingOrder", UpdateSortingOrder);
		L.RegFunction("ReGetCompenent", ReGetCompenent);
		L.RegFunction("AddComponent", AddComponent);
		L.RegFunction("RemoveConponent", RemoveConponent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateSortingOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ParticleOrderAutoSorter obj = (ParticleOrderAutoSorter)ToLua.CheckObject<ParticleOrderAutoSorter>(L, 1);
			obj.UpdateSortingOrder();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ReGetCompenent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ParticleOrderAutoSorter obj = (ParticleOrderAutoSorter)ToLua.CheckObject<ParticleOrderAutoSorter>(L, 1);
			obj.ReGetCompenent();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ParticleOrderAutoSorter obj = (ParticleOrderAutoSorter)ToLua.CheckObject<ParticleOrderAutoSorter>(L, 1);
			UnityEngine.ParticleSystem arg0 = (UnityEngine.ParticleSystem)ToLua.CheckObject(L, 2, typeof(UnityEngine.ParticleSystem));
			obj.AddComponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveConponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ParticleOrderAutoSorter obj = (ParticleOrderAutoSorter)ToLua.CheckObject<ParticleOrderAutoSorter>(L, 1);
			UnityEngine.ParticleSystem arg0 = (UnityEngine.ParticleSystem)ToLua.CheckObject(L, 2, typeof(UnityEngine.ParticleSystem));
			obj.RemoveConponent(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

