//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SorterTagWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SorterTag), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetSorter", GetSorter);
		L.RegFunction("SetSorter", SetSorter);
		L.RegFunction("SetSpace3D", SetSpace3D);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Space3D", get_Space3D, set_Space3D);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSorter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			SorterTag obj = (SorterTag)ToLua.CheckObject<SorterTag>(L, 1);
			int o = obj.GetSorter();
			LuaDLL.lua_pushinteger(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSorter(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SorterTag obj = (SorterTag)ToLua.CheckObject<SorterTag>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSorter(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSpace3D(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SorterTag obj = (SorterTag)ToLua.CheckObject<SorterTag>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.SetSpace3D(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Space3D(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SorterTag obj = (SorterTag)o;
			int ret = obj.Space3D;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Space3D on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Space3D(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SorterTag obj = (SorterTag)o;
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.Space3D = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Space3D on a nil value");
		}
	}
}

