//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SpriteAssetWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SpriteAsset), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetSpriteByName", GetSpriteByName);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("SpriteAssetInfos", get_SpriteAssetInfos, set_SpriteAssetInfos);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSpriteByName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			SpriteAsset obj = (SpriteAsset)ToLua.CheckObject<SpriteAsset>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.Sprite o = obj.GetSpriteByName(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SpriteAssetInfos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteAsset obj = (SpriteAsset)o;
			System.Collections.Generic.List<SpriteAssetInfo> ret = obj.SpriteAssetInfos;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SpriteAssetInfos on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_SpriteAssetInfos(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SpriteAsset obj = (SpriteAsset)o;
			System.Collections.Generic.List<SpriteAssetInfo> arg0 = (System.Collections.Generic.List<SpriteAssetInfo>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<SpriteAssetInfo>));
			obj.SpriteAssetInfos = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SpriteAssetInfos on a nil value");
		}
	}
}

