//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_Extensions_UGUIModelWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.UI.Extensions.UGUIModel), typeof(UnityEngine.EventSystems.UIBehaviour));
		L.RegFunction("OnDrag", OnDrag);
		L.RegFunction("SetCameraEffect", SetCameraEffect);
		L.RegFunction("IsModelExist", IsModelExist);
		L.RegFunction("SetModelAt", SetModelAt);
		L.RegFunction("GetModelAt", GetModelAt);
		L.RegFunction("UpdateModelShownIndex", UpdateModelShownIndex);
		L.RegFunction("ImportSetting", ImportSetting);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("OnPointerDown", OnPointerDown);
		L.RegFunction("OnPointerUp", OnPointerUp);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("cameraHeightOffset", get_cameraHeightOffset, set_cameraHeightOffset);
		L.RegVar("onModelClick", get_onModelClick, set_onModelClick);
		L.RegVar("Model", get_Model, set_Model);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDrag(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnDrag(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCameraEffect(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetCameraEffect(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsModelExist(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			bool o = obj.IsModelExist(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetModelAt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			ColaFramework.ISceneCharacter arg1 = (ColaFramework.ISceneCharacter)ToLua.CheckObject<ColaFramework.ISceneCharacter>(L, 3);
			obj.SetModelAt(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetModelAt(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			ColaFramework.ISceneCharacter o = obj.GetModelAt(arg0);
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateModelShownIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.UpdateModelShownIndex(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ImportSetting(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
				obj.ImportSetting();
				return 0;
			}
			else if (count == 2)
			{
				UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.ImportSetting(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityEngine.UI.Extensions.UGUIModel.ImportSetting");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerDown(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)ToLua.CheckObject<UnityEngine.UI.Extensions.UGUIModel>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerUp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_cameraHeightOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			float ret = obj.cameraHeightOffset;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraHeightOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_onModelClick(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			System.Action<string> ret = obj.onModelClick;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onModelClick on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Model(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			UnityEngine.Transform ret = obj.Model;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Model on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_cameraHeightOffset(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.cameraHeightOffset = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index cameraHeightOffset on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_onModelClick(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			System.Action<string> arg0 = (System.Action<string>)ToLua.CheckDelegate<System.Action<string>>(L, 2);
			obj.onModelClick = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index onModelClick on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_Model(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.UI.Extensions.UGUIModel obj = (UnityEngine.UI.Extensions.UGUIModel)o;
			UnityEngine.Transform arg0 = (UnityEngine.Transform)ToLua.CheckObject<UnityEngine.Transform>(L, 2);
			obj.Model = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Model on a nil value");
		}
	}
}

